In [18]:
import numpy as np

def matrix_norm(matrix):
  sum = 0
  for i in range(len(matrix)):
    sum += abs(matrix[i])
  return max(sum)

def generate_symmetrical_matrix(l, r, n):
    a = np.random.uniform(l, r, (n, n))
    a = np.tril(a) + np.tril(a, -1).T
    return a

def increase_diag_elems(a, diag):
    n = len(a)
    for i in range(0, len(a)):
        a[i][i] = diag * sum(abs(a[i][j]) if j != i else 0 for j in range(n))
    return a

def calc_diagonal_dominance(a):
  degree = max(abs(a[i][i]) - sum(abs(a[i][j]) if j != i else 0 for j in range(len(a))) for i in range(len(a)))
  return degree > 0

In [19]:
def LU(A):
    # A = L * U
    n = len(A)
    L, U = np.zeros_like(A), np.zeros_like(A)
    for i in range(n): L[i][i] = 1.0

    for i in range(n):
        for j in range(n):
            if i <= j:
                s = sum(L[i][k] * U[k][j] for k in range(i))
                U[i][j] = A[i][j] - s
            elif i > j:
                s = sum(L[i][k] * U[k][j] for k in range(j))
                L[i][j] = (A[i][j] - s) / U[j][j]
    return L, U

n = 5
A = generate_symmetrical_matrix(10, 40, n)
A = increase_diag_elems(A, 3)
print(f'matrix A:\n{A}\n')

L, U = LU(A)
print(f'matrix L:\n{L}\n')
print(f'matrix U:\n{U}\n')
print(f'matrix L*U:\n{L @ U}\n')
lu_err = matrix_norm(A - L @ U)
print(f'LU decomposition error: {lu_err}\n')

matrix A:
[[222.53668464  11.11210648  19.84806812  28.66898444  14.54973584]
 [ 11.11210648 288.49680622  34.66397586  17.03148003  33.3580397 ]
 [ 19.84806812  34.66397586 290.67565234  20.8791964   21.50064373]
 [ 28.66898444  17.03148003  20.8791964  260.16497722  20.14199819]
 [ 14.54973584  33.3580397   21.50064373  20.14199819 268.6512524 ]]

matrix L:
[[1.         0.         0.         0.         0.        ]
 [0.04993382 1.         0.         0.         0.        ]
 [0.0891901  0.11694332 1.         0.         0.        ]
 [0.12882813 0.05417734 0.05789395 1.         0.        ]
 [0.06538129 0.11332672 0.05750448 0.06106299 1.        ]]

matrix U:
[[222.53668464  11.11210648  19.84806812  28.66898444  14.54973584]
 [  0.         287.94193631  33.67288603  15.59992816  32.63151583]
 [  0.           0.         284.96758216  16.49789956  16.3869136 ]
 [  0.           0.           0.         254.67131441  15.55099105]
 [  0.           0.           0.           0.         262.110038

РК 1 - Вычисление определителя матрицы через LU-
разложение

In [15]:
def get_matrix_det(L, U):
  det = 1
  n = len(U)
  for i in range(n):
    det *= U[i][i]
  return det

lib_det = np.linalg.det(A)
print(f'matrix det through NumPy: {lib_det}')
lu_det = get_matrix_det(L, U)
print(f'matrix det through LU decomposition: {lu_det}')
print(f'are they equal: {np.allclose(lib_det, lu_det)}')

matrix det through NumPy: 2954493058240.5845
matrix det through LU decomposition: 2954493058240.5923
are they equal: True
